### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Band-hi#2]
[Infografía gestión de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Band-hi/files/9420127/Infografia.gestion.de.proyectos.de.software.pdf)

**Comment by kirus21** [comment]
18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
